[2024-05-24T00:21:36.322+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-24T00:21:36.330+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.transform_Temperature_Data manual__2024-05-24T00:21:33.579269+00:00 [queued]>
[2024-05-24T00:21:36.334+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.transform_Temperature_Data manual__2024-05-24T00:21:33.579269+00:00 [queued]>
[2024-05-24T00:21:36.334+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-24T00:21:36.341+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_Temperature_Data> on 2024-05-24 00:21:33.579269+00:00
[2024-05-24T00:21:36.346+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=244) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-24T00:21:36.347+0000] {standard_task_runner.py:63} INFO - Started process 255 to run task
[2024-05-24T00:21:36.347+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'transform_Temperature_Data', 'manual__2024-05-24T00:21:33.579269+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/***_dag.py', '--cfg-path', '/tmp/tmpe1kzo7v3']
[2024-05-24T00:21:36.348+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask transform_Temperature_Data
[2024-05-24T00:21:36.370+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline.transform_Temperature_Data manual__2024-05-24T00:21:33.579269+00:00 [running]> on host 7f18484bb9a3
[2024-05-24T00:21:36.415+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='transform_Temperature_Data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-24T00:21:33.579269+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-24T00:21:33.579269+00:00'
[2024-05-24T00:21:36.416+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-24T00:21:36.516+0000] {log.py:232} WARNING - [2024-05-24 00:21:36,516] [INFO] - Data transformation successful.
[2024-05-24T00:21:36.516+0000] {base_logger.py:19} INFO - Data transformation successful.
[2024-05-24T00:21:36.516+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-24T00:21:36.516+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-24T00:21:36.521+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=transform_Temperature_Data, run_id=manual__2024-05-24T00:21:33.579269+00:00, execution_date=20240524T002133, start_date=20240524T002136, end_date=20240524T002136
[2024-05-24T00:21:36.560+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-24T00:21:36.572+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
